version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_stripe_api_service
    volumes:
      - .:/djstrippr
    ports:
      - "8000:8000"
    env_file:
      - djstrippr/.env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - djstrippr/.env

volumes:
  postgres_data: